sudo : required
services:
  - docker
before_install:
  - docker build -t  swathireddyg54/docker-react-app -f Dockerfile.dev .
script:
  - docker run swathireddyg54/docker-react-app npm run test -- --coverage
  