language: generic
services:
  - docker
before_install:
  - docker build -t  swathireddyg54/docker-react-app -f Dockerfile.dev .
script:
  - docker run -e CI=true swathireddyg54/docker-react-app npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-app"
  env: "DockerReactApp-env "
  bucket_name: "elasticbeanstalk-us-east-2-423762574823"
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
